### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by TowerScience** [apache2c/intro-data-capstone-biodiversity#2]
Overall: Meets Expectations 13/16
Code 4 - Your code looks great and gets the job done, no problems there
Presentation 3 - Its a serviceable presentation but could have some formatting and colors to spice it up
Hypothesis 2 - You've got the ideas right, but should fully state your hypothesis so the readers know what you were trying to solve for.
Interpretations 4 - Good job understanding the conclusions and coming up with ideas for future studies.

Overall you did pretty good, most importantly the code looks great. There are some opportunities to improve the presentation however.

**Comment by apache2c** [comment]
The course did not include PowerPoint and did not specify a need to "spice it up."

The course also did not specify the need for a hypothesis.

Closing issue.
